description = "Tcl Ada Shell demos"
name = "tash_demos"
licenses = "GPL-2.0-or-later WITH GCC-exception-2.0"
version = "8"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

project-files = ["tash_demos.gpr"]
executables = [
               "freq",
               "futurevalue",
               "hello_world",
               "tashell",
               "timer",
               "twashell",
               "watching",
               "wordify"
              ]

[[depends-on]]
tash = "*"

[[pins]]
tash = { path='..' }
